// Maintenance command: update hashes only after provenance and artwork review.
import {readFile,writeFile,readdir} from 'node:fs/promises';
import {createHash} from 'node:crypto';
const root=new URL('../public/assets/',import.meta.url);
const mappings={'loam':'dirt','meadow':'grass_top','meadow-edge':'grass_side','rock':'stone_generic','pebble':'gravel','dune':'sand_ugly','bark':'oak_log_side','rings':'oak_log_top','boards':'oak_planks','foliage':'oak_leaves','frost':'snow','void':'obsidian','pane':'glass'};
const assets=[];
for(const [local,original] of Object.entries(mappings))assets.push({path:`textures/terrain/${local}.png`,name:'16x16 Block Texture Set',creator:'ARoachIFoundOnMyPillow',kind:'external',license:'CC0-1.0',repository:'https://github.com/EBonura/voxide',commit:'066f483baacbf926507b4fcaa63caab46e524f51',sourcePath:`assets/pack/blocks/blocks/${original}.png`,sourceUrl:'https://opengameart.org/content/16x16-block-texture-set',licenseEvidence:'https://opengameart.org/content/16x16-block-texture-set',verification:'Byte-identical to blocks/'+original+'.png in https://opengameart.org/sites/default/files/blocks_2.zip; creator page identifies CC0; artwork manually reviewed.',modified:false,use:'Terrain atlas and block item icons'});
for(const name of (await readdir(new URL('textures/original/',root))).sort())assets.push({path:'textures/original/'+name,name:name.slice(0,-4),creator:'Lapis Obsidian Client contributors',kind:'original',license:'CC0-1.0',sourcePath:'client/scripts/generate-originals.mjs',sourceUrl:'repository:client/scripts/generate-originals.mjs',licenseEvidence:'LICENSE.md',modified:false,verification:'Original deterministic 16x16 pixel designs, seed index +17; no imported artwork.',use:'Atlas fallback, blocks, tools, items, entities, UI and particles'});
assets.push({path:'audio/events.json',name:'Original synthesized sound designs',creator:'Lapis Obsidian Client contributors',kind:'original',license:'CC0-1.0',sourcePath:'client/public/assets/audio/events.json',sourceUrl:'repository:client/public/assets/audio/events.json',licenseEvidence:'LICENSE.md',modified:false,verification:'Original waveform/frequency/envelope parameters; no recordings or sound downloads.',use:'Footsteps, block/tool actions, pickup, UI, entities, ambient and environmental audio'});
for(const a of assets)a.sha256=createHash('sha256').update(await readFile(new URL(a.path,root))).digest('hex');
await writeFile(new URL('manifest.json',root),JSON.stringify({version:1,reviewed:'2026-10-08',assets},null,2)+'\n');
console.log('Asset provenance manifest:',assets.length,'files');
