[package]
name = "lapis-obsidian-client"
version.workspace = true
edition.workspace = true
license.workspace = true

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
lapis-bridge = { path = "../bridge" }
serde_json = "1"
tokio = { version = "1", features = ["rt-multi-thread"] }
