#ifndef H_LAPIS_PROTOCOL
#define H_LAPIS_PROTOCOL

#define LAPIS_PROTOCOL_VERSION 772
#define LAPIS_MINECRAFT_VERSION "1.21.8"
#define LAPIS_STRINGIFY_INNER(x) #x
#define LAPIS_STRINGIFY(x) LAPIS_STRINGIFY_INNER(x)

#endif
