#!/usr/bin/env python3
"""Embed verified event PCM for native/WebAudio and generate web material names."""
import argparse
import hashlib
import json
import pathlib
import re
import struct
import wave

ROOT = pathlib.Path(__file__).resolve().parents[1]


def generate(destination):
    mapping = json.loads((ROOT / 'assets/sound-map.json').read_text())
    manifest = {a['destination_filename']: a for a in json.loads((ROOT / 'assets/manifest.json').read_text())['assets']}
    groups = mapping['events']
    # A sample shared by multiple event groups is embedded only once.
    names = list(dict.fromkeys(name for group in groups.values() for name in group))
    pcm = {}
    for name in set(names + [n for g in mapping['material'].values() for n in g]):
        if not re.fullmatch('[a-z_]+[1-9][0-9]*', name):
            raise ValueError('Invalid sound name')
        path = 'assets/audio/' + name + '.wav'
        entry = manifest[path]
        if entry['license'] != 'CC0-1.0' or hashlib.sha256((ROOT / path).read_bytes()).hexdigest() != entry['sha256']:
            raise ValueError('Sound provenance/hash mismatch: ' + path)
        with wave.open(str(ROOT / path)) as wav:
            if (wav.getnchannels(), wav.getsampwidth(), wav.getframerate()) != (1, 2, mapping['sample_rate']):
                raise ValueError('Unexpected PCM format: ' + path)
            data = wav.readframes(wav.getnframes())
        pcm[name] = struct.unpack('<' + 'h' * (len(data) // 2), data)
    lines = ['/* Generated by tools/embed_audio.py. Recording credits: assets/manifest.json. */',
             '#ifndef LC_SOUND_DATA_H', '#define LC_SOUND_DATA_H',
             'struct LapisRecordedClip { const cc_int16* samples; int count; };',
             'struct LapisRecordedGroup { const int* clips; int count; };',
             f'#define LAPIS_SOUND_RATE {mapping["sample_rate"]}']
    for index, name in enumerate(names):
        samples = pcm[name]
        lines.append(f'static const cc_int16 lapis_pcm_{index}[] = {{ /* {name}.wav */')
        lines += [','.join(str(s) for s in samples[i:i+24]) + ',' for i in range(0, len(samples), 24)]
        lines.append('};')
    lines.append('static const struct LapisRecordedClip Lapis_RecordedClips[] = {')
    lines += [f'    {{lapis_pcm_{i}, {len(pcm[name])}}},' for i, name in enumerate(names)]
    lines.append('};')
    for index, (group, clips) in enumerate(groups.items()):
        lines += [f'#define LAPIS_SOUND_{group.upper()} {index}',
                  'static const int lapis_group_' + str(index) + '[] = {' + ','.join(str(names.index(n)) for n in clips) + '};']
    lines.append('static const struct LapisRecordedGroup Lapis_RecordedGroups[] = {')
    lines += [f'    {{lapis_group_{i}, {len(clips)}}},' for i, clips in enumerate(groups.values())]
    lines += ['};', f'#define LAPIS_RECORDED_COUNT {len(names)}', f'#define LAPIS_SOUND_GROUPS {len(groups)}', '#endif']
    destination.mkdir(parents=True, exist_ok=True)
    (destination / 'LapisSoundData.h').write_text('\n'.join(lines) + '\n')
    # Audio_Web.c consumes exactly the same variant list as native packaging.
    materials = ['/* Generated from assets/sound-map.json. */',
                 'static const struct SoundID { int group; const char* name; } sounds_list[] = {']
    for kind in ('step', 'dig'):
        if kind == 'dig': materials.append('    { SOUND_NONE, NULL },')
        for group, clips in mapping['material'].items():
            if not group.startswith(kind + '_'): continue
            material = group.split('_', 1)[1].upper()
            materials += [f'    {{ SOUND_{material}, "{name}" }},' for name in clips]
    materials.append('};')
    (destination / 'LapisMaterialSounds.h').write_text('\n'.join(materials) + '\n')


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('destination', type=pathlib.Path)
    generate(parser.parse_args().destination)
